apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
  namespace: example
  labels:
    app: helloflask-app
  annotations:
spec:
  selector:
    matchLabels:
      app: helloflask-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: helloflask-app
    spec:
      containers:
      - name: helloflask-app
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080